In [1]:

import pandas as pd
import os

In [2]:
import kagglehub

path = kagglehub.dataset_download("zusmani/rainfall-in-pakistan")
print("Path to dataset files:", path)

Path to dataset files: /kaggle/input/datasets/zusmani/rainfall-in-pakistan

In [3]:
# Load dataset
path = "/kaggle/input/datasets/zusmani/rainfall-in-pakistan"
file_path = os.path.join(path, os.listdir(path)[0])

df = pd.read_csv(file_path)
df.head()

   Rainfall - (MM)   Year     Month
0          40.4258   1901   January
1          12.3022   1901  February
2          25.5119   1901     March
3          14.2942   1901     April
4          38.3046   1901       May

In [4]:
# Clean columns
df.columns = df.columns.str.strip()
df = df.rename(columns={'Rainfall - (MM)': 'rainfall'})
df.head()

   rainfall  Year     Month
0   40.4258  1901   January
1   12.3022  1901  February
2   25.5119  1901     March
3   14.2942  1901     April
4   38.3046  1901       May

In [5]:
# Convert Month
df['Month'] = pd.to_datetime(df['Month'], format='%B').dt.month
df.head()

   rainfall  Year  Month
0   40.4258  1901      1
1   12.3022  1901      2
2   25.5119  1901      3
3   14.2942  1901      4
4   38.3046  1901      5

In [6]:
# Create date column
df['date'] = pd.to_datetime(df[['Year','Month']].assign(DAY=1))
df.head()

   rainfall  Year  Month       date
0   40.4258  1901      1 1901-01-01
1   12.3022  1901      2 1901-02-01
2   25.5119  1901      3 1901-03-01
3   14.2942  1901      4 1901-04-01
4   38.3046  1901      5 1901-05-01

In [7]:
# Sort
df = df.sort_values('date')

In [8]:
# Remove missing
df = df.dropna()

print("Cleaned Data:")
df.head()

Cleaned Data:

   rainfall  Year  Month       date
0   40.4258  1901      1 1901-01-01
1   12.3022  1901      2 1901-02-01
2   25.5119  1901      3 1901-03-01
3   14.2942  1901      4 1901-04-01
4   38.3046  1901      5 1901-05-01